export const GET_BOOKED_PLOTS_SUCCESS = "GET_BOOKED_PLOTS_SUCCESS";
export const GET_BOOKED_PLOTS_PENDING = "GET_BOOKED_PLOTS_PENDING";
export const GET_BOOKED_PLOTS_FAILURE = "GET_BOOKED_PLOTS_FAILURE";
